import React, { useState } from "react";
import { Link, useNavigate, useSearchParams } from "react-router-dom";
import { useAuth } from "../../context/AuthContext";

export const Signup = () => {
  const [fullName, setFullName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState(""); const [isSubmitting, setIsSubmitting] = useState(false); const [error, setError] = useState("");
  const [searchParams] = useSearchParams(); const selectedPlan = searchParams.get("plan"); const referralCode = String(searchParams.get("ref") || "").trim(); const isProIntent = selectedPlan === "pro";
  const { signup, loginWithGoogle, user } = useAuth(); const navigate = useNavigate();
  const getFriendlyErrorMessage = (errorCode) => { switch (errorCode) { case "auth/email-already-in-use": return "An account with this email address already exists."; case "auth/invalid-email": return "Please enter a valid email address."; case "auth/operation-not-allowed": return "Email/password accounts are not enabled. Please contact support."; case "auth/weak-password": return "Password is too weak. Please use a stronger password."; case "auth/popup-closed-by-user": return "Google sign-up popup was closed before completing."; case "auth/network-request-failed": return "Network error. Please check your internet connection."; default: return "Failed to create account. Please check your details and try again."; } };
  const applyReferral = async () => { if (!referralCode || !user) return; try { const token = await user.getIdToken(); await fetch("/api/referral", { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ code: referralCode }) }); } catch (err) { console.warn("Referral attribution failed", err); } };
  const handleSignup = async (e) => { e.preventDefault(); setError(""); if (!fullName.trim() || !email.trim() || !password || !confirmPassword) return setError("Please fill in all required fields."); if (password.length < 8) return setError("Password must be at least 8 characters long."); if (password !== confirmPassword) return setError("Passwords do not match."); setIsSubmitting(true); try { await signup(email, password, fullName.trim()); await applyReferral(); navigate("/dashboard"); } catch (err) { setError(getFriendlyErrorMessage(err?.code)); } finally { setIsSubmitting(false); } };
  const handleGoogleSignup = async () => { setError(""); setIsSubmitting(true); try { await loginWithGoogle(); await applyReferral(); navigate("/dashboard"); } catch (err) { setError(getFriendlyErrorMessage(err?.code)); } finally { setIsSubmitting(false); } };

  return <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-indigo-50 flex flex-col justify-center py-12 sm:px-6 lg:px-8 text-slate-900"><div className="sm:mx-auto sm:w-full sm:max-w-md text-center"><Link to="/" className="text-3xl font-extrabold tracking-tight text-blue-700">PromptStudio AI</Link><p className="mt-2 text-sm text-slate-500">{isProIntent ? "Create your account to continue toward PromptStudio Pro." : "Create your free account to get started."}</p></div>
    <div className="mt-8 sm:mx-auto sm:w-full sm:max-w-md"><div className="rounded-2xl border border-slate-200 bg-white p-8 shadow-xl sm:px-10">
      {isProIntent && <div className="mb-5 rounded-xl border border-blue-100 bg-blue-50 p-4"><p className="text-sm font-bold text-blue-900">⭐ Pro selected</p><p className="mt-1 text-xs leading-relaxed text-blue-700">Create your account now and continue to secure billing after signup.</p></div>}
      {referralCode && <div className="mb-5 rounded-xl border border-emerald-100 bg-emerald-50 p-4"><p className="text-sm font-bold text-emerald-900">🎁 Referral reward</p><p className="mt-1 text-xs leading-relaxed text-emerald-700">You joined through an invite. If the referral is valid, your bonus credits will be added automatically after signup.</p></div>}
      {error && <div className="mb-4 flex items-start rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700"><span className="mr-2">⚠️</span><span>{error}</span></div>}
      <form className="space-y-5" onSubmit={handleSignup}><div><label className="block text-sm font-medium text-slate-700">Full Name</label><input type="text" required value={fullName} onChange={(e) => setFullName(e.target.value)} placeholder="Alex Morgan" className="mt-1 block w-full rounded-lg border border-slate-200 bg-white px-3.5 py-2.5 text-sm text-slate-900 shadow-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100" /></div><div><label className="block text-sm font-medium text-slate-700">Email address</label><input type="email" required value={email} onChange={(e) => setEmail(e.target.value)} placeholder="name@company.com" className="mt-1 block w-full rounded-lg border border-slate-200 bg-white px-3.5 py-2.5 text-sm text-slate-900 shadow-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100" /></div><div><label className="block text-sm font-medium text-slate-700">Password</label><input type="password" required value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Minimum 8 characters" className="mt-1 block w-full rounded-lg border border-slate-200 bg-white px-3.5 py-2.5 text-sm text-slate-900 shadow-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100" /></div><div><label className="block text-sm font-medium text-slate-700">Confirm Password</label><input type="password" required value={confirmPassword} onChange={(e) => setConfirmPassword(e.target.value)} placeholder="Re-enter password" className="mt-1 block w-full rounded-lg border border-slate-200 bg-white px-3.5 py-2.5 text-sm text-slate-900 shadow-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100" /></div><button type="submit" disabled={isSubmitting} className="mt-2 flex w-full items-center justify-center rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white shadow-sm transition-colors hover:bg-blue-700 disabled:cursor-not-allowed disabled:opacity-50">{isSubmitting ? "Creating Account..." : "Create Free Account"}</button></form>
      <div className="mt-6"><div className="relative"><div className="absolute inset-0 flex items-center"><div className="w-full border-t border-slate-200" /></div><div className="relative flex justify-center text-xs uppercase"><span className="bg-white px-2 text-slate-400">Or continue with</span></div></div><div className="mt-6"><button type="button" onClick={handleGoogleSignup} disabled={isSubmitting} className="flex w-full items-center justify-center rounded-lg border border-slate-200 bg-white px-4 py-2.5 text-sm font-medium text-slate-700 shadow-sm transition-colors hover:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-50"><svg className="mr-2 h-5 w-5" viewBox="0 0 24 24"><path fill="#4285F4" d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z" /><path fill="#FBBC05" d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.06H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.94l2.85-2.22.81-.63z" /><path fill="#EA4335" d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.06l3.66 2.84c.87-2.6 3.3-4.52 6.16-4.52z" /></svg>Continue with Google</button></div></div>
      <p className="mt-6 text-center text-xs text-slate-500">Already have an account? <Link to="/login" className="font-semibold text-blue-700 hover:text-blue-800">Sign in</Link></p>
    </div></div></div>;
};
export default Signup;
