import React, { useState } from "react";
import { Link, useNavigate, useSearchParams } from "react-router-dom";
import { useAuth } from "../../context/AuthContext";
import { auth } from "../../firebase";

export const Signup = () => {
  const [fullName, setFullName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState(""); const [isSubmitting, setIsSubmitting] = useState(false); const [error, setError] = useState("");
  const [searchParams] = useSearchParams(); const selectedPlan = searchParams.get("plan"); const referralCode = String(searchParams.get("ref") || "").trim(); const isProIntent = selectedPlan === "pro";
  const { signup, loginWithGoogle } = useAuth(); const navigate = useNavigate();
  const getFriendlyErrorMessage = (errorCode) => { switch (errorCode) { case "auth/email-already-in-use": return "An account with this email address already exists."; case "auth/invalid-email": return "Please enter a valid email address."; case "auth/operation-not-allowed": return "Email/password accounts are not enabled. Please contact support."; case "auth/weak-password": return "Password is too weak. Please use a stronger password."; case "auth/popup-closed-by-user": return "Google sign-up popup was closed before completing."; case "auth/network-request-failed": return "Network error. Please check your internet connection."; default: return "Failed to create account. Please check your details and try again."; } };
  const applyReferral = async () => { if (!referralCode || !auth.currentUser) return; try { const token = await auth.currentUser.getIdToken(); await fetch("/api/admin?action=referral-public", { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ code: referralCode }) }); } catch (err) { console.warn("Referral attribution failed", err); } };
  const handleSignup = async (e) => { e.preventDefault(); setError(""); if (!fullName.trim() || !email.trim() || !password || !confirmPassword) return setError("Please fill in all required fields."); if (password.length < 8) return setError("Password must be at least 8 characters long."); if (password !== confirmPassword) return setError("Passwords do not match."); setIsSubmitting(true); try { await signup(email, password, fullName.trim()); await applyReferral(); navigate("/dashboard"); } catch (err) { setError(getFriendlyErrorMessage(err?.code)); } finally { setIsSubmitting(false); } };
  const handleGoogleSignup = async () => { setError(""); setIsSubmitting(true); try { await loginWithGoogle(); await applyReferral(); navigate("/dashboard"); } catch (err) { setError(getFriendlyErrorMessage(err?.code)); } finally { setIsSubmitting(false); } };

  return <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-indigo-50 flex flex-col justify-center py-12 sm:px-6 lg:px-8 text-slate-900"><div className="sm:mx-auto sm:w-full sm:max-w-md text-center"><Link to="/" className="text-3xl font-extrabold tracking-tight text-blue-700">PromptStudio AI</Link><p className="mt-2 text-sm text-slate-500">{isProIntent ? "Create your account to continue toward PromptStudio Pro." : "Create your free account to get started."}</p></div>
    <div className="mt-8 sm:mx-auto sm:w-full sm:max-w-md"><div className="rounded-2xl border border-slate-200 bg-white p-8 shadow-xl sm:px-10">
      {isProIntent && <div className="mb-5 rounded-xl border border-blue-100 bg-blue-50 p-4"><p className="text-sm font-bold text-blue-900">⭐ Pro selected</p><p className="mt-1 text-xs leading-relaxed text-blue-700">Create your account now and continue to secure billing after signup.</p></div>}
      {referralCode && <div className="mb-5 rounded-xl border border-emerald-100 bg-emerald-50 p-4"><p className="text-sm font-bold text-emerald-900">🎁 Referral reward</p><p className="mt-1 text-xs leading-relaxed text-emerald-700">You joined through an invite. If the referral is valid, your bonus credits will be added automatically after signup.</p></div>}
      {error && <div className="mb-4 flex items-start rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700"><span className="mr-2">⚠️</span><span>{error}</span></div>}
      <form className="space-y-5" onSubmit={handleSignup}><div><label className="block text-sm font-medium text-slate-700">Full Name</label><input type="text" required value={fullName} onChange={(e) => setFullName(e.target.value)} placeholder="Alex Morgan" className="mt-1 block w-full rounded-lg border border-slate-200 bg-white px-3.5 py-2.5 text-sm text-slate-900 shadow-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100" /></div><div><label className="block text-sm font-medium text-slate-700">Email address</label><input type="email" required value={email} onChange={(e) => setEmail(e.target.value)} placeholder="name@company.com" className="mt-1 block w-full rounded-lg border border-slate-200 bg-white px-3.5 py-2.5 text-sm text-slate-900 shadow-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100" /></div><div><label className="block text-sm font-medium text-slate-700">Password</label><input type="password" required value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Minimum 8 characters" className="mt-1 block w-full rounded-lg border border-slate-200 bg-white px-3.5 py-2.5 text-sm text-slate-900 shadow-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100" /></div><div><label className="block text-sm font-medium text-slate-700">Confirm Password</label><input type="password" required value={confirmPassword} onChange={(e) => setConfirmPassword(e.target.value)} placeholder="Re-enter password" className="mt-1 block w-full rounded-lg border border-slate-200 bg-white px-3.5 py-2.5 text-sm text-slate-900 shadow-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100" /></div><button type="submit" disabled={isSubmitting} className="mt-2 flex w-full items-center justify-center rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white shadow-sm transition-colors hover:bg-blue-700 disabled:cursor-not-allowed disabled:opacity-50">{isSubmitting ? "Creating Account..." : "Create Free Account"}</button></form>
      <div className="mt-6"><div className="relative"><div className="absolute inset-0 flex items-center"><div className="w-full border-t border-slate-200" /></div><div className="relative flex justify-center text-xs uppercase"><span className="bg-white px-2 text-slate-400">Or continue with</span></div></div><div className="mt-6"><button type="button" onClick={handleGoogleSignup} disabled={isSubmitting} className="flex w-full items-center justify-center rounded-lg border border-slate-200 bg-white px-4 py-2.5 text-sm font-medium text-slate-700 shadow-sm transition-colors hover:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-50"><span className="mr-2 text-base font-black text-blue-600">G</span>Continue with Google</button></div></div>
      <p className="mt-6 text-center text-xs text-slate-500">Already have an account? <Link to="/login" className="font-semibold text-blue-700 hover:text-blue-800">Sign in</Link></p>
    </div></div></div>;
};
export default Signup;
