export const PRICING_PLANS = [
  {
    id: 'free',
    name: 'Free',
    price: '₹0',
    period: 'forever',
    description: 'Try PromptStudio with 3 prompt generations and 1 image-to-prompt each day.',
    features: [
      '3 Prompt Generations per Day',
      '1 Image → Prompt per Day',
      'Works with ChatGPT',
      'Works with Claude',
      'Works with Gemini',
      'Copy Generated Prompt',
    ],
    cta: 'Start Free',
    highlighted: false,
  },
  {
    id: 'pro',
    name: 'Pro',
    price: '₹79',
    period: 'per month',
    annualPrice: '₹499',
    annualPeriod: 'per year',
    description: 'For creators and professionals who use PromptStudio every day.',
    features: [
      '25 prompt generations per day',
      '20 image-to-prompt generations per month',
      'Optimized for ChatGPT, Claude and Gemini',
      'Priority improvements',
      'Premium workflows and features',
    ],
    cta: 'Upgrade to Pro',
    highlighted: true,
  },
  {
    id: 'credits',
    name: 'Creator Credits',
    price: '₹49',
    period: 'one-time',
    description: 'Pay only when you need more. Built especially for image-to-prompt creators.',
    features: [
      '25 credits for ₹49',
      '60 credits for ₹99 · Best Value',
      '2 credits per standard prompt',
      '5 credits per Image → Prompt',
      'No recurring payment',
      'Credits never expire',
    ],
    cta: 'Get Creator Credits',
    highlighted: false,
  },
];
