export const PRICING_PLANS = [
  {
    id: 'free',
    name: 'Free',
    price: '₹0',
    period: 'forever',
    description: 'Try PromptStudio with 3 prompt generations every day.',
    features: [
      '3 Prompt Generations per Day',
      'Works with ChatGPT',
      'Works with Claude',
      'Works with Gemini',
      'Copy Generated Prompt',
    ],
    cta: 'Current Plan',
    highlighted: false,
  },
  {
    id: 'pro',
    name: 'Pro',
    price: '₹79',
    period: 'per month',
    annualPrice: '₹499',
    annualPeriod: 'per year',
    description: 'For creators and professionals who use PromptStudio every day.',
    features: [
      '100 prompt generations per day',
      '100 image-prompt generations per month',
      'Optimized for ChatGPT, Claude and Gemini',
      'Priority improvements',
      'Premium workflows and features',
    ],
    cta: 'Upgrade to Pro',
    highlighted: true,
  },
  {
    id: 'credits',
    name: 'Credits',
    price: '₹99',
    period: 'one-time',
    description: 'A simple one-time boost when you need more prompts without a subscription.',
    features: [
      '25 prompt credits',
      'Use when Free quota is exhausted',
      'No recurring payment',
      'Credits remain available until used',
    ],
    cta: 'Buy 25 Credits',
    highlighted: false,
  },
];
