import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { useAuth } from "../../context/AuthContext";

export default function ReferralRewardToast() {
  const { user } = useAuth(); const [reward, setReward] = useState(null);
  useEffect(() => { const onReward = (event) => { if (event.detail?.credits > 0) setReward(event.detail); }; window.addEventListener("promptstudio:referral-reward", onReward); return () => window.removeEventListener("promptstudio:referral-reward", onReward); }, []);
  useEffect(() => { if (!user) return undefined; let active = true; (async () => { try { const token = await user.getIdToken(); const response = await fetch("/api/admin?action=referral-public", { headers: { Authorization: `Bearer ${token}` } }); const body = await response.json().catch(() => ({})); if (!response.ok || !active) return; const latest = (body.referrals || []).filter((item) => item.role === "referrer" && item.status === "completed").sort((a, b) => new Date(b.completedAt || b.createdAt || 0) - new Date(a.completedAt || a.createdAt || 0))[0]; if (!latest?.id) return; const key = `promptstudio:referral-seen:${user.uid}`; const seen = localStorage.getItem(key); if (seen === latest.id) return; localStorage.setItem(key, latest.id); if (Number(latest.referrerReward || 0) > 0) setReward({ side: "referrer", credits: Number(latest.referrerReward) }); } catch (_) {} })(); return () => { active = false; }; }, [user]);
  if (!reward) return null;
  return <div className="fixed inset-x-4 bottom-5 z-[80] mx-auto max-w-lg rounded-3xl border border-indigo-200 bg-white p-5 text-slate-900 shadow-2xl shadow-indigo-900/15 sm:inset-x-auto sm:right-6 sm:mx-0"><div className="flex gap-4"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-indigo-100 text-xl">🎁</div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><div><p className="text-base font-black">Referral reward credited</p><p className="mt-0.5 text-sm text-slate-600">+{reward.credits} credits added to your wallet.</p></div><button type="button" onClick={() => setReward(null)} className="text-slate-400 hover:text-slate-700" aria-label="Close referral reward notification">✕</button></div><p className="mt-3 text-xs text-slate-500">Your referral was successfully completed and the reward has been recorded.</p><div className="mt-4 flex flex-wrap gap-2"><Link to="/transactions" onClick={() => setReward(null)} className="rounded-xl bg-blue-600 px-3.5 py-2.5 text-xs font-black text-white hover:bg-blue-500">View transaction</Link><Link to="/referral" onClick={() => setReward(null)} className="rounded-xl border border-slate-200 px-3.5 py-2.5 text-xs font-black text-slate-700 hover:bg-slate-50">View referrals</Link></div></div></div></div>;
}
