import { useEffect } from "react";
import { Routes, Route, Navigate, useLocation, useSearchParams } from "react-router-dom";
import Landing from "./pages/Landing/Landing"; import Login from "./pages/Auth/Login"; import Signup from "./pages/Auth/Signup"; import ForgotPassword from "./pages/Auth/ForgotPassword"; import Dashboard from "./pages/Dashboard/Dashboard"; import Account from "./pages/Account/Account"; import PromptBuilder from "./pages/Builder/PromptBuilder"; import SharedPrompt from "./pages/SharedPrompt/SharedPrompt"; import WorkflowLibrary from "./pages/Workflows/WorkflowLibrary"; import Admin from "./pages/Admin/Admin"; import ReferralRewards from "./pages/Admin/ReferralRewards"; import About from "./pages/About/About"; import Help from "./pages/Help/Help"; import Feedback from "./pages/Feedback/Feedback"; import Contact from "./pages/Contact/Contact"; import Terms from "./pages/Legal/Terms"; import Privacy from "./pages/Legal/Privacy"; import Refund from "./pages/Legal/Refund"; import ImageToPrompt from "./pages/ImageToPrompt/ImageToPrompt"; import ReferenceCoding from "./pages/ReferenceCoding/ReferenceCoding"; import { ProtectedRoute } from "./components/ProtectedRoute"; import { RuntimeFeatureRoute } from "./components/RuntimeFeatureRoute"; import PromptHistory from "./pages/Result/PromptHistory"; import Transactions from "./pages/Transactions/Transactions"; import AppLayout from "./components/layout/AppLayout"; import SupportWidget from "./components/support/SupportWidget"; import PaymentSuccessToast from "./components/billing/PaymentSuccessToast"; import Referral from "./pages/Referral/Referral"; import ReferralRewardToast from "./components/referral/ReferralRewardToast";

const PAGE_TITLES = { "/": "PromptStudio AI — Better prompts for every AI", "/image-to-prompt": "Image to Prompt Generator | PromptStudio AI", "/reference-coding": "Reference Coding | PromptStudio AI", "/about": "About | PromptStudio AI", "/help": "Help Center | PromptStudio AI", "/contact": "Contact | PromptStudio AI", "/feedback": "Feedback | PromptStudio AI", "/terms": "Terms | PromptStudio AI", "/privacy": "Privacy | PromptStudio AI", "/refund": "Refund Policy | PromptStudio AI", "/login": "Log in | PromptStudio AI", "/signup": "Create your account | PromptStudio AI", "/forgot-password": "Reset password | PromptStudio AI", "/builder": "Builder | PromptStudio AI", "/dashboard": "Dashboard | PromptStudio AI", "/history": "History | PromptStudio AI", "/account": "Account | PromptStudio AI", "/workflows": "Workflows | PromptStudio AI", "/transactions": "Transactions | PromptStudio AI", "/referral": "Referral Rewards | PromptStudio AI", "/admin/referrals": "Founder Referral Rewards | PromptStudio AI" };
function RouteEffects() { const { pathname } = useLocation(); useEffect(() => { const title = PAGE_TITLES[pathname]; if (title) document.title = title; window.scrollTo({ top: 0, left: 0, behavior: "instant" }); }, [pathname]); return null; }
const withAppLayout = (element) => <ProtectedRoute><AppLayout>{element}</AppLayout></ProtectedRoute>;
const withRuntimeFeature = (feature, element) => <ProtectedRoute><RuntimeFeatureRoute feature={feature}><AppLayout>{element}</AppLayout></RuntimeFeatureRoute></ProtectedRoute>;
function BuilderRoute() { const [searchParams] = useSearchParams(); if (searchParams.get("mode") === "coding") return <Navigate to="/reference-coding" replace />; return withAppLayout(<PromptBuilder />); }
export default function App() { return <><RouteEffects /><Routes>
  <Route path="/" element={<Landing />} /><Route path="/image-to-prompt" element={<ImageToPrompt />} /><Route path="/reference-coding" element={<ReferenceCoding />} /><Route path="/login" element={<Login />} /><Route path="/signup" element={<Signup />} /><Route path="/forgot-password" element={<ForgotPassword />} /><Route path="/p/:id" element={<SharedPrompt />} /><Route path="/about" element={<About />} /><Route path="/help" element={<Help />} /><Route path="/contact" element={<Contact />} /><Route path="/feedback" element={<Feedback />} /><Route path="/terms" element={<Terms />} /><Route path="/privacy" element={<Privacy />} /><Route path="/refund" element={<Refund />} />
  <Route path="/dashboard" element={withAppLayout(<Dashboard />)} /><Route path="/builder" element={<BuilderRoute />} /><Route path="/workflows" element={withAppLayout(<WorkflowLibrary />)} /><Route path="/account" element={withAppLayout(<Account />)} /><Route path="/transactions" element={withAppLayout(<Transactions />)} /><Route path="/referral" element={withAppLayout(<Referral />)} /><Route path="/history" element={withRuntimeFeature("promptHistory", <PromptHistory />)} /><Route path="/admin" element={<ProtectedRoute><Admin /></ProtectedRoute>} /><Route path="/admin/referrals" element={<ProtectedRoute><ReferralRewards /></ProtectedRoute>} /><Route path="*" element={<Navigate to="/" replace />} />
</Routes><SupportWidget /><PaymentSuccessToast /><ReferralRewardToast /></>; }
