import React, { useEffect, useState } from "react";
import { Navigate, Link } from "react-router-dom";
import { auth } from "../../firebase";

export default function ReferralRewards() {
  const [allowed, setAllowed] = useState(null); const [config, setConfig] = useState(null); const [referrals, setReferrals] = useState([]); const [busy, setBusy] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const api = async (options = {}) => { const token = await auth.currentUser?.getIdToken(); const res = await fetch("/api/admin?action=referrals", { ...options, headers: { ...(options.headers || {}), Authorization: `Bearer ${token}`, "Content-Type": "application/json" } }); const body = await res.json().catch(() => ({})); if (!res.ok) throw new Error(body.message || "Request failed."); return body; };
  const load = async () => { setBusy(true); setError(""); try { const claim = await auth.currentUser?.getIdTokenResult(true); if (claim?.claims?.admin !== true) { setAllowed(false); return; } setAllowed(true); const body = await api(); setConfig(body.config); setReferrals(body.referrals || []); } catch (e) { setError(e.message || "Could not load referral controls."); } finally { setBusy(false); } };
  useEffect(() => { load(); }, []);
  const save = async () => { setSaving(true); setError(""); setMessage(""); try { const body = await api({ method: "PUT", body: JSON.stringify(config) }); setConfig(body.config); setMessage("Referral reward rules saved securely."); const refreshed = await api(); setReferrals(refreshed.referrals || []); } catch (e) { setError(e.message || "Could not save referral rewards."); } finally { setSaving(false); } };
  if (busy) return <main className="min-h-screen bg-slate-950 p-10 text-white">Checking founder access…</main>;
  if (allowed === false) return <Navigate to="/admin" replace />;
  return <main className="min-h-screen bg-slate-50 px-4 py-8 text-slate-950 sm:px-6"><div className="mx-auto max-w-6xl"><header className="rounded-3xl bg-slate-950 p-7 text-white shadow-xl"><p className="text-xs font-black uppercase tracking-[0.2em] text-indigo-300">PromptStudio · Founder Control</p><h1 className="mt-2 text-3xl font-black">Referral Rewards</h1><p className="mt-2 max-w-2xl text-sm text-slate-400">Control the referral program without changing code. Reward credits are applied atomically and each referred account can be rewarded only once.</p><Link to="/admin" className="mt-5 inline-flex rounded-xl border border-slate-700 px-4 py-2 text-sm font-bold">← Back to Control Center</Link></header>
    {error && <div className="mt-5 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</div>}{message && <div className="mt-5 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-700">{message}</div>}
    {config && <section className="mt-6 grid gap-6 lg:grid-cols-[1fr_1.4fr]"><div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Reward rules</h2><p className="mt-1 text-sm text-slate-500">These values control future successful referral signups.</p><label className="mt-6 flex items-center justify-between rounded-xl border border-slate-200 bg-slate-50 p-4 text-sm font-bold">Program enabled<input type="checkbox" checked={config.enabled} onChange={(e) => setConfig({ ...config, enabled: e.target.checked })} className="h-5 w-5" /></label><label className="mt-4 block text-sm font-bold">Referrer reward (credits)<input type="number" min="0" max="1000" step="1" value={config.referrerCredits} onChange={(e) => setConfig({ ...config, referrerCredits: Number(e.target.value) })} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-3 outline-none focus:border-indigo-400" /></label><label className="mt-4 block text-sm font-bold">New user reward (credits)<input type="number" min="0" max="1000" step="1" value={config.refereeCredits} onChange={(e) => setConfig({ ...config, refereeCredits: Number(e.target.value) })} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-3 outline-none focus:border-indigo-400" /></label><div className="mt-4 rounded-xl bg-slate-50 p-4 text-xs leading-5 text-slate-600">Reward trigger: <strong>successful signup</strong>. Rewards are server-side and idempotent. Existing referrals are never re-rewarded when you change the settings.</div><button disabled={saving} onClick={save} className="mt-6 w-full rounded-xl bg-indigo-600 px-4 py-3 text-sm font-black text-white disabled:opacity-50">{saving ? "Saving securely…" : "Save referral rules"}</button></div>
      <div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="text-xl font-black">Referral activity</h2><p className="mt-1 text-sm text-slate-500">Latest successful attributions.</p></div><span className="rounded-full bg-indigo-50 px-3 py-1 text-xs font-black text-indigo-700">{referrals.length} total shown</span></div><div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-slate-200 text-xs uppercase tracking-wide text-slate-500"><th className="px-3 py-3">Referrer</th><th className="px-3 py-3">New user</th><th className="px-3 py-3">Rewards</th><th className="px-3 py-3">Status</th></tr></thead><tbody>{referrals.length ? referrals.map((r) => <tr key={r.id} className="border-b border-slate-100"><td className="px-3 py-3 font-mono text-xs">{r.referrerUid}</td><td className="px-3 py-3 font-mono text-xs">{r.refereeUid}</td><td className="px-3 py-3 font-bold">+{r.referrerReward} / +{r.refereeReward}</td><td className="px-3 py-3"><span className="rounded-full bg-emerald-50 px-2 py-1 text-xs font-bold text-emerald-700">{r.status}</span></td></tr>) : <tr><td colSpan="4" className="px-3 py-12 text-center text-sm text-slate-500">No referrals yet.</td></tr>}</tbody></table></div></div></section>}
  </div></main>;
}
