import { useEffect, useState } from 'react';
import { auth } from '../../firebase';

export default function UserManagement({ api }) {
  const [users,setUsers]=useState([]); const [q,setQ]=useState(''); const [selected,setSelected]=useState(null); const [credits,setCredits]=useState(25); const [note,setNote]=useState(''); const [trialUntil,setTrialUntil]=useState(''); const [coupon,setCoupon]=useState({code:'',type:'percent',value:10,maxUses:1,expiresAt:''}); const [message,setMessage]=useState('');
  const load=async()=>{const b=await api('/api/admin-user-management');setUsers(b.users||[]);}; useEffect(()=>{load().catch(e=>setMessage(e.message));},[]);
  const act=async(action,extra={})=>{if(!selected)return;await api('/api/admin-user-management',{method:'POST',body:JSON.stringify({action,uid:selected.id,credits,...extra})});setMessage('User updated.');await load();};
  const createCoupon=async()=>{await api('/api/admin-coupons',{method:'POST',body:JSON.stringify(coupon)});setMessage('Coupon created.');setCoupon({code:'',type:'percent',value:10,maxUses:1,expiresAt:''});};
  const filtered=users.filter(u=>`${u.email||''} ${u.displayName||''} ${u.id}`.toLowerCase().includes(q.toLowerCase()));
  return <section className="mt-6 space-y-6"><div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Founder User Management</h2><p className="mt-1 text-sm text-slate-500">Private founder controls for trials, volunteer access, credits and account handling. Every change is audit logged.</p>{message&&<p className="mt-3 rounded-xl bg-emerald-50 p-3 text-sm font-bold text-emerald-700">{message}</p>}<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search email, name or UID" className="mt-5 w-full rounded-xl border border-slate-200 px-3 py-2 text-sm"/><div className="mt-4 grid gap-3">{filtered.map(u=><button key={u.id} onClick={()=>setSelected(u)} className={`rounded-2xl border p-4 text-left ${selected?.id===u.id?'border-indigo-400 bg-indigo-50':'border-slate-200'}`}><div className="flex justify-between"><span className="font-black">{u.email||u.displayName||u.id}</span><span className="text-xs font-bold">{u.plan||'free'} · {u.credits??0} credits</span></div><p className="mt-1 text-xs text-slate-500">{u.id}</p></button>)}</div></div>
  {selected&&<div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-lg font-black">Controls for {selected.email||selected.id}</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><label className="text-sm font-bold">Credits<input type="number" min="1" value={credits} onChange={e=>setCredits(Number(e.target.value))} className="mt-1 w-full rounded-xl border px-3 py-2"/></label><button onClick={()=>act('grantCredits')} className="rounded-xl bg-indigo-600 px-4 py-2 text-sm font-bold text-white">🎁 Grant credits</button><button onClick={()=>act('removeCredits')} className="rounded-xl border px-4 py-2 text-sm font-bold">Remove credits</button><button onClick={()=>act('setPlan',{plan:'pro'})} className="rounded-xl border px-4 py-2 text-sm font-bold">⭐ Give Pro</button><label className="text-sm font-bold">Trial expiry<input type="datetime-local" value={trialUntil} onChange={e=>setTrialUntil(e.target.value)} className="mt-1 w-full rounded-xl border px-3 py-2"/></label><button onClick={()=>act('setTrial',{trialUntil:trialUntil?new Date(trialUntil).toISOString():null})} className="rounded-xl bg-emerald-600 px-4 py-2 text-sm font-bold text-white">🆓 Set trial</button><button onClick={()=>act('resetQuota')} className="rounded-xl border px-4 py-2 text-sm font-bold">🔄 Reset quota</button><button onClick={()=>act('suspend')} className="rounded-xl border border-red-200 px-4 py-2 text-sm font-bold text-red-700">🚫 Suspend</button><button onClick={()=>act('unsuspend')} className="rounded-xl border px-4 py-2 text-sm font-bold">Restore account</button></div><label className="mt-4 block text-sm font-bold">Founder note<textarea value={note} onChange={e=>setNote(e.target.value)} className="mt-1 w-full rounded-xl border px-3 py-2" placeholder="Why this user received an exception..."/><button onClick={()=>act('note',{note})} className="mt-2 rounded-xl border px-4 py-2 text-sm font-bold">Save note</button></label></div>}
  <div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-lg font-black">Coupons</h2><p className="mt-1 text-sm text-slate-500">Create controlled founder coupons without changing Razorpay pricing.</p><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><input placeholder="CODE" value={coupon.code} onChange={e=>setCoupon({...coupon,code:e.target.value})} className="rounded-xl border px-3 py-2"/><select value={coupon.type} onChange={e=>setCoupon({...coupon,type:e.target.value})} className="rounded-xl border px-3 py-2"><option value="percent">% discount</option><option value="credits">Bonus credits</option></select><input type="number" min="1" value={coupon.value} onChange={e=>setCoupon({...coupon,value:Number(e.target.value)})} className="rounded-xl border px-3 py-2"/><input type="number" min="1" value={coupon.maxUses} onChange={e=>setCoupon({...coupon,maxUses:Number(e.target.value)})} className="rounded-xl border px-3 py-2"/><button onClick={createCoupon} className="rounded-xl bg-slate-950 px-4 py-2 text-sm font-bold text-white">Create coupon</button></div></div></section>;
}
